name: r6api
description: Dart wrapper around Rainbow Six Siege stats API, inspired by r6api.js
version: 0.0.1
homepage: https://github.com/PoloLacoste/r6api.dart
repository: https://github.com/PoloLacoste/r6api.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.0

dev_dependencies:
  test: '>=1.15.0 <2.0.0'
